function [BW,maskedRGBImage] = createMask_universal_1_15_Lab(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 23-Jan-2017
%------------------------------------------------------


% Convert RGB image to chosen color space
RGB = im2double(RGB);
cform = makecform('srgb2lab', 'AdaptedWhitePoint', whitepoint('D65'));
I = applycform(RGB,cform);

% Define thresholds for channel 1 based on histogram settings
%channel1Min = 31.443;
%channel1Max = 100.000;
%channel1Min = 30;
%channel1Max = 100.000;
channel1Min = 20; %30 10
channel1Max = 100;%100

% Define thresholds for channel 2 based on histogram settings
%channel2Min = -24.225;
%channel2Max = 23.123;
channel2Min = -20; %-25
channel2Max = 40; % 25 

% Define thresholds for channel 3 based on histogram settings
%channel3Min = -20.568;
%channel3Max = 35.106;
channel3Min = -35; %-20
channel3Max = 40; %35

% Create mask based on chosen histogram thresholds
BW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;
